### ISSUE TITLE
Reach out about SIParCS Participation in CESM Conference 

### ISSUE THREAD

**Issue by philipc2** [philipc2/siparcs-project-13#15]

**Comment by philipc2** [comment]
@rytam2

**Comment by rytam2** [comment]
Agenda: https://www.cesm.ucar.edu/events/351/agenda

**Monday Sessions that sounds interesting:** 
Morning 10:30 AM - 12:10 PM: Plenary Speakers
- Jane Mulcahy, UK Met Office, "UKESM2 development pathway, progress and plans towards CMIP7 "
- Veronika Eyring, DLR, “Understanding and Modelling the Earth System with Machine Learning”
- Maria Rugenstein, Colorado State University, "How the Good and the Bad conspire to the Ugly: trends of surface temperatures and TOA radiation in climate models and observations"

Afternoon 1:30 PM - 5:00 PM: [Atmosphere Working Group](https://www.cesm.ucar.edu/sites/default/files/2024-05/amwg-cesm-workshop-2024docx.pdf): Focusing on the different parameter schemes, automated tuning and numerics

**Tuesday Sessions that sounds interesting and no conflict with NWSC:** 
Morning 8:30 AM - 10:30 AM: [Harnessing Machine Learning for CESM ](https://www.cesm.ucar.edu/sites/default/files/2024-05/machine-learning-cesm-workshop-2024docx_0.pdf): ML techniques is pretty translatable across applications
Afternoon 3:30 - 5:30 PM: [High-resolution](https://www.cesm.ucar.edu/sites/default/files/2024-05/high-ultra-high-cesm-workshop-2024_0.pdf): Interested in learning what people are doing with higher resolution (e.g. with focuses on cloud-permitting scales) and what visualization needs may come up as models evolve towards higher resolution. 

**Wednesday Sessions that sounds interesting (will minimize conflict with Hackathon):** 
Morning 8:30 AM - 10:30 AM: [Climate Variability](https://www.cesm.ucar.edu/sites/default/files/2024-05/cvcwg-cesm-workshop-2024docx.pdf)
